### ISSUE TITLE
DO NOT USE THIS, ITS VIRUS!!!

### ISSUE THREAD

**Issue by SteavenGamerYT** [anhonor/GuildedCreator#1]
someone used it in guilded minecraft server and got hacked

DO NOT USE IT

I WARN YOU, DO NOT USE IT

**Comment by Ryan-shamu-YT** [comment]
I am in the server, noone used it

**Comment by Ryan-shamu-YT** [comment]
Im checking out the python code to see this

**Comment by anhonor** [comment]
pure nonsense, this user wants to be acknowledged by people and seeks attention a little too often. you are not cool, you are not helpful, and please refrain from creating illegitimate issues. thank you!

<img width="688" alt="Screen Shot 2024-02-20 at 8 02 11 AM" src="https://github.com/anhonor/GuildedCreator/assets/154564843/7e3baf4c-b6c8-4068-8651-b7ef249e2db0">
